# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c10555bc037ae91ec02481b910069af960bd3ee253e48303e09e0864f7cf5aea43476c949800a818b37ab49e24877f0eb69b0fd917f6ee1750ab78026fdd5a5b

test:
  secret_key_base: e931f91a0afc674d3b1c22124c5df7843b583d6ffa8f8362fca9e90ca4d206042b71c8e8a517794163c5ed972f32981563a9604438a1b7240fd86f86e62d52e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
